exports.menuTitles = {
	'rolls': 'Роллы',
	'sushi': 'Суши',
	'pizza': 'Пицца',
	'noodles': 'Лапша',
	'desserts': 'Десерты',
	'salads': 'Салаты',
	'salati': 'Салаты',
	'soups': 'Супы',
	'bluda_na_grile': 'Блюда на гриле',
	'vtoroe': 'Вторые блюда',
	'garnir': 'Гарнир',
	'deserti': 'Десерты',
	'napitki': 'Напитки',
	'soysi': 'Соусы',
	'hleb': 'Хлеб',
};